name: .NET

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore library/full/src ; dotnet restore library/lang/src
    - name: Restore resources
      run: . .\download_resources.ps1
    - name: Build
      run: dotnet build library/full/src -c Release ; dotnet build library/lang/src -c Release
    - name: Pack
      run: nuget pack library/full/nuget/SharpOpenJTalk.nuspec ; nuget pack library/lang/nuget/SharpOpenJTalk.Lang.nuspec
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: SharpOpenJTalk*.nupkg

